name: deploy
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Build Container
      run: docker build -t ghcr.io/koldorney/portkolio:latest --push ./svelte

  deploy:
    runs-on: ubuntu-latest
    needs: publish

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Pull from GHCR
      run: docker pull ghcr.io/koldorney/portkolio

    - name: Tag for GCR
      run: docker tag ghcr.io/koldorney/portkolio us-east1-docker.pkg.dev/verdant-branch-424915-r9/basic/portkolio

    - name: Push to GCR
      run: docker push us-east1-docker.pkg.dev/verdant-branch-424915-r9/basic/portkolio