name: Publish and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your publish steps here
      # For example, building and pushing a Docker image to a registry

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        run: |
            cd svelte
            docker build -t ghcr.io/koldorney/portkolio:latest .
            docker push ghcr.io/koldorney/portkolio:latest
  

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Pull image from GitHub Container Registry
        run: docker pull ghcr.io/koldorney/portkolio:latest

      - name: Tag Docker image for Google Artifact Registry
        run: docker tag ghcr.io/koldorney/portkolio:latest us-central1-docker.pkg.dev/verdant-branch-424915-r9/github/portkolio:latest

      - name: Push Docker image to Google Artifact Registry
        run: docker push us-central1-docker.pkg.dev/verdant-branch-424915-r9/github/portkolio:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy portkolio \
            --image us-central1-docker.pkg.dev/verdant-branch-424915-r9/github/portkolio:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated